#!/usr/bin/env bash
# Installs, configures, and starts the server

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx

echo "Holberton School" | sudo tee /var/www/html/index
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
