#!/usr/bin/env bash
# install and configure HAproxy

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen 540-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 9845-web-02 34.236.134.42:80 check\n\tserver 9845-web-01 3.235.171.76:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
