#!/usr/bin/env bash
# script that displays To infinity and beyond indefinitely

i=0
while [ $i -eq 0 ]
do
        echo "To infinity and beyond"
        sleep 2
	trap 'echo "i am invincible!!!"' SIGTERM
done
