#!/usr/bin/env bash

# script displays the visitor ip along with the HTTP status Code

awk '{ print $1, $9 }' /home/ghostface/alx-system_engineering-devops/0x04-loops_conditions_and_parsing/apache-access.log
